manage:
  debug: False
  path_temp: temp
  path_resources: resources
  error_arg: "Argument error."
  step_sleep: 1.5
  snapshot_build: build
  snapshot_final: final

host:
  network_gateway: 10.10.10.1
  network_cidr: 8
  network_dns: 1.1.1.1
  container_memory: 2048
  container_disk: 32
  container_pass: crcx3909
  container_template_path: /var/lib/vz/template/cache/debian11.tar.zst
  container_template_url: http://ftp.cn.debian.org/proxmox/images/system/debian-11-standard_11.7-1_amd64.tar.zst
  ssh_keys: /root/.ssh/authorized_keys
  ssh_hosts: /root/.ssh/known_hosts

server:
  id: 200
  name: TÜV SÜD
  network_hostname: server
  network_ip: 10.10.10.200
  network_mac: AA:BB:CC:DD:EE:00
  port_ui: 80
  port_ledger: 8000
  port_acapy_1: 9000
  port_acapy_2: 10000
  port_redis: 7000
  port_tails: 6543
  db_user: root
  db_pass: 12345
  db_name: fu27soma
  log_acapy: aca-py.log
  log_redis: redis.log
  log_indy: indy.log
  log_tails: tails.log
  log_app: app.log

node1:
  id: 201
  name: Siemens
  network_hostname: node1
  network_ip: 10.10.10.201
  network_mac: AA:BB:CC:DD:EE:01
  port_ui: 80
  port_acapy_1: 9000
  port_acapy_2: 10000
  port_redis: 7000
  port_tails: 6543
  log_acapy: aca-py.log
  log_redis: redis.log
  log_app: app.log

node2:
  id: 202
  name: ATS Automation
  network_hostname: node2
  network_ip: 10.10.10.202
  network_mac: AA:BB:CC:DD:EE:02
  port_ui: 80
  port_acapy_1: 9000
  port_acapy_2: 10000
  port_redis: 7000
  port_tails: 6543
  log_acapy: aca-py.log
  log_redis: redis.log
  log_app: app.log
  