conf:
  gateway: 10.10.136.254
  memory: 1024
  disk: 16
  passwd: 12345
  ssh: /root/.ssh/authorized_keys
  tails: 6543

server:
  hostname: server
  id: 200
  ip: 10.10.136.200
  endpoint: 9000
  ledger: fu27soma

node1:
  hostname: node1
  id: 201
  ip: 10.10.136.201
  endpoint: 9001
  admin: 10001

node2:
  hostname: node2
  id: 202
  ip: 10.10.136.202
  endpoint: 9002
  admin: 10002