manage:
  debug: False
  path_temp: temp
  path_resources: resources
  error_arg: "Argument error."

host:
  network_gateway: 10.10.10.1
  network_cidr: 8
  network_dns: 1.1.1.1
  container_memory: 1024
  container_disk: 16
  container_pass: crcx3909
  container_template_path: /var/lib/vz/template/cache/debian11.tar.zst
  container_template_url: http://ftp.cn.debian.org/proxmox/images/system/debian-11-standard_11.7-1_amd64.tar.zst
  ssh: /root/.ssh/authorized_keys

server:
  id: 200
  network_hostname: server
  network_ip: 10.10.10.200
  network_mac: AA:BB:CC:DD:EE:00
  ledger_endpoint: 9000
  ledger_name: fu27soma
  db_user: root
  db_pass: 12345
  db_name: fu27soma

node1:
  id: 201
  name: Company A
  network_hostname: node1
  network_ip: 10.10.10.201
  network_mac: AA:BB:CC:DD:EE:01
  acapy_endpoint1: 9000
  acapy_endpoint2: 10000
  tails_endpoint: 6543
  redis_endpoint: 6379
  redis_pass: 12345

node2:
  id: 202
  name: Company B
  network_hostname: node2
  network_ip: 10.10.10.202
  network_mac: AA:BB:CC:DD:EE:02
  acapy_endpoint1: 9000
  acapy_endpoint2: 10000
  tails_endpoint: 6543
  redis_endpoint: 6379
  redis_pass: 12345
  