manage:
  debug: False
  path_temp: temp
  path_resources: resources
  error_arg: "Argument error."
  step_sleep: 1.5

host:
  network_gateway: 10.10.10.1
  network_cidr: 8
  network_dns: 1.1.1.1
  container_memory: 1024
  container_disk: 16
  container_pass: crcx3909
  container_template_path: /var/lib/vz/template/cache/debian11.tar.zst
  container_template_url: http://ftp.cn.debian.org/proxmox/images/system/debian-11-standard_11.7-1_amd64.tar.zst
  ssh_keys: /root/.ssh/authorized_keys
  ssh_hosts: /root/.ssh/known_hosts

server:
  id: 200
  name: fu27soma
  network_hostname: server
  network_ip: 10.10.10.200
  network_mac: AA:BB:CC:DD:EE:00
  port_ui: 80
  port_ledger: 9000
  db_user: root
  db_pass: 12345
  db_name: fu27soma
  port_redis: 7000
  pass_redis: 12345

node1:
  id: 201
  name: Company A
  network_hostname: node1
  network_ip: 10.10.10.201
  network_mac: AA:BB:CC:DD:EE:01
  port_ui: 80
  port_acapy_1: 9000
  port_acapy_2: 10000
  port_tails: 6543
  port_redis: 7000
  file_log: aca-py.log

node2:
  id: 202
  name: Company B
  network_hostname: node2
  network_ip: 10.10.10.202
  network_mac: AA:BB:CC:DD:EE:02
  port_ui: 80
  port_acapy_1: 9000
  port_acapy_2: 10000
  port_tails: 6543
  port_redis: 7000
  file_log: aca-py.log
  